[package]
name = "rename"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.8"
dialoguer = "0.11"
regex = "1.5"
chrono = "0.4"